# Generated by Django 4.0 on 2023-04-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
    ]
