# Generated by Django 4.0 on 2023-04-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt_api_app', '0002_rename_myuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='terms_cond',
            field=models.BooleanField(),
        ),
    ]
