# Generated by Django 4.0 on 2023-04-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt_api_app', '0003_alter_user_terms_cond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='terms_cond',
            new_name='terms_condition',
        ),
    ]
